import Head from "next/head";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";

export default function Home({ exploreData, cardData }) {
  console.log(exploreData);
  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <section className="explore container-md">
        <h2>Explore Nearby</h2>
        <div className="explore__content">
          {exploreData?.map((explore, index) => {
            return <SmallCard key={index} {...explore} />;
          })}
        </div>
      </section>

      <section className="live container-md">
        <h2>Live Anywhere</h2>
        <div className="live__content">
          {cardData?.map((card, index) => {
            return <MediumCard key={index} {...card} />;
          })}
        </div>
      </section>
      <LargeCard
        img="https://links.papareact.com/4cj"
        title="the Greatest Outdoors"
        desc="Wishlist created bu airbnb"
        btnText="get inspiration"
      />
      <Footer />
    </div>
  );
}

export const getStaticProps = async () => {
  const res1 = await fetch("https://jsonkeeper.com/b/4G1G");
  const exploreData = await res1.json();

  const res2 = await fetch("https://links.papareact.com/zp1");
  const cardData = await res2.json();

  return {
    props: { exploreData, cardData },
  };
};
